// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLIPBDmQav023IUA3-coHrm22LRD3trY',
    appId: '1:74027221610:android:d01603414aa34c3f720013',
    messagingSenderId: '74027221610',
    projectId: 'mosalla-79ae7',
    storageBucket: 'mosalla-79ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFINcI3lH6hUjCBwBY_FNdpqApvZGHz3g',
    appId: '1:74027221610:ios:290dba6a3d334c85720013',
    messagingSenderId: '74027221610',
    projectId: 'mosalla-79ae7',
    storageBucket: 'mosalla-79ae7.appspot.com',
    iosClientId: '74027221610-fo9t3kl6mann6rdalfmsdessn7dfm90p.apps.googleusercontent.com',
    iosBundleId: 'io.github.sohaibnomanahmed.mosalla',
  );
}
